apiVersion: apps/v1
kind: Deployment
metadata:
  name: rautaki-fire-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rautaki-fire
  template:
    metadata:
      labels:
        app: rautaki-fire
    spec:
      containers:
      - name: rautaki-fire
        image: gcr.io/booming-pride-412719/fire-front:v1.7
        env:
        - name: PORT
          value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: rautaki-fire-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: rautaki-fire-ci
  ports:
  - name: rautaki-fire-ci
    protocol: TCP
    port: 80
    targetPort: 8081